### ISSUE TITLE
Test failures with boost 1.63 package.

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [libbitcoin/libbitcoin-database#118]
make  check-TESTS
    make[1]: Entering directory `/home/alice/rpmbuild/BUILD/libbitcoin-database-master'
    make[2]: Entering directory `/home/alice/rpmbuild/BUILD/libbitcoin-database-master'
    FAIL: libbitcoin_database_test_runner.sh
    make[3]: Entering directory `/home/alice/rpmbuild/BUILD/libbitcoin-database-master'
    make[3]: Nothing to be done for `all'.
    make[3]: Leaving directory `/home/alice/rpmbuild/BUILD/libbitcoin-database-master'
    ============================================================================
    Testsuite summary for libbitcoin-database 4.0.0
    ============================================================================
    # TOTAL: 1
    # PASS:  0
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  1
    # XPASS: 0
    # ERROR: 0
    ============================================================================
    See ./test-suite.log
    Please report to eric@***
    ============================================================================

-=-

CentOS 7 x86_64
gcc 4.8.5
boost 1.63.0
libbitcoin 4.0.0 from yesterday (make check passes there)

**Comment by evoskuil** [comment]
Thanks, please post `test-suite.log` which should have specifics. Also note that the test suite [successfully executed in Travis](https://travis-ci.org/libbitcoin/libbitcoin-database/builds/205663770).

**Comment by evoskuil** [comment]
Also, please perform a build of `libbitcoin-database` with its install.sh, using a non-sudo `--prefix` build and setting the `--build-boost` option. This will isolate the build as much as possible from the environment and will execute the database tests.

**Comment by AliceWonderMiscreations** [comment]
That's test.log (test-suite.log just has the test suite summary) - I'll try the install.sh tonight and post results.

[test.log.txt](https://github.com/libbitcoin/libbitcoin-database/files/812142/test.log.txt)

**Comment by evoskuil** [comment]
Thanks, is this is little endian platform?

**Comment by AliceWonderMiscreations** [comment]
Yes it is little endian - Xeon E3

just ran install.sh w/o build boost and got the same error.

However with the --build-boost option it passes, so the difference is boost - it doesn't like how my boost was built.

The boost I have is built on my system but using a src.rpm from Fedora Rawhide so I'll have to look at their options and patches and see if I can figure out which one is causing the problem.

**Comment by evoskuil** [comment]
Ok, great - thanks for the info.

That's a bit of a relief, because the error made no sense to me at all. Not all of the libraries are yet fully verified on other than LE platforms (though the base library is). So I figured we might have an issue in the store, but sort of grasping there.

It's not obvious to me how boost could be affecting it. Please keep us posted.

**Comment by AliceWonderMiscreations** [comment]
Yes, boost I tried making a boost 1.63.0 RPM w/ no patches, also had same failure.

I am presently working on trying to get boost 1.58.0 packaged for test environment - if that doesn't work I'll go down to 1.57.0 (what the install script built)

If that doesn't work then it is a boost packaging issue.

If boost 1.58.0 does work I'll bump up one at a time until I find the version of boost where the issue starts.

I'll figure it out. But it works with install.sh using boost 1.57.0 from source

**Comment by AliceWonderMiscreations** [comment]
Okay just like to confirm that using boost 1.58.0 did work. I need to clean up that packaging of boost a little before I start walking up the boost versions, but its packaged the same way as the 1.63.0 that failed so I suspect there is a changed behavior in boost. I'll find the version where it breaks so maybe the changelog for that version can shed some light.

**Comment by atweiden** [comment]
Looks like the test failures are the same on [Arch](https://aur.archlinux.org/packages/libbitcoin-database) with boost 1.6.3: http://ix.io/oQm

**Comment by evoskuil** [comment]
Another boost issue, though doesn't look related:

https://github.com/libbitcoin/libbitcoin/issues/733

**Comment by evoskuil** [comment]
Closing as complete.
