### ISSUE TITLE
Remove hash from block_database::unindex or check that hash matches 

### ISSUE THREAD

**Issue by kulpreet** [libbitcoin/libbitcoin-database#238]
https://github.com/libbitcoin/libbitcoin-database/blob/a0f64d2f904ec1e53e1b5b93eb8ede4102a8198f/src/databases/block_database.cpp#L442

The presence of hash as the first parameter is confusing, especially since it is eventually ignored in the method.

Should we make one of the following two changes?

1. Remove hash from the method, making it explicit that unindex only removes from the top of the index.

2. Keep hash as the first parameter, but check that the hash matches the link found by read_index.

In the case of 1, why should we even pass the height then? Just `unindex(true)` or `unindex(false)` should do the trick. I might be missing how unindex is used in the data_base. But as I understand, it does seem like hash is redundant, the calls to unindex from data_base are passing in a hash that is anyway obtained from block_database using the height.

For the moment, I am writing tests with a not_found hash since it is ignored anyway. It should avoid confusion in the future.

**Comment by kulpreet** [comment]
Left a small note about this here: https://github.com/libbitcoin/libbitcoin-database/pull/239/files#diff-77c85c6e2e58160d55c89ab0582a212aR169

**Comment by evoskuil** [comment]
The hash should be asserted in debug builds, using a DEBUG_ONLY parameter. This would require the tests to populate the hash in order to not fail in debug build test runs.
