### ISSUE TITLE
FAIL libbitcoin_database_test_runner.sh

### ISSUE THREAD

**Issue by veleiro** [libbitcoin/libbitcoin-database#93]
Hi, I received the following error while running install.sh

```
=================================================
   libbitcoin-database 3.0.0: ./test-suite.log
=================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: libbitcoin_database_test_runner.sh
========================================

FAIL libbitcoin_database_test_runner.sh (exit status: 201)
Makefile:2423: recipe for target 'test-suite.log' failed
make[2]: *** [test-suite.log] Error 1
make[2]: Leaving directory '/home/veleiro/Projects/bitcoin/libbitcoin/libbitcoin-database/build-libbitcoin-database/libbitcoin-database'
Makefile:2529: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 2
make[1]: Leaving directory '/home/veleiro/Projects/bitcoin/libbitcoin/libbitcoin-database/build-libbitcoin-database/libbitcoin-database'
Makefile:2735: recipe for target 'check-am' failed
make: *** [check-am] Error 2
Running 37 test cases...
Platform: linux
Compiler: GNU C++ version 6.2.0 20161109
STL     : GNU libstdc++ version 20161109
Boost   : 1.62.0

```

Host system Debian Stretch

Any ideas?

**Comment by evoskuil** [comment]
The network tests are not unit tests, they test live connections on testnet. They are therefore not generally reliable.

**Comment by veleiro** [comment]
ok, thanks.
i don't understand if it installed properly.  Every time I run 'make' after this, i get the following error:

`  CXX      src/utility/src_libbitcoin_c_la-variable_uint_size.lo
src/utility/variable_uint_size.cpp:22:58: fatal error: bitcoin/bitcoin/utility/variable_uint_size.hpp: No such file or directory
 #include <bitcoin/bitcoin/utility/variable_uint_size.hpp>
                                                          ^
compilation terminated.
Makefile:1541: recipe for target 'src/utility/src_libbitcoin_c_la-variable_uint_size.lo' failed
make: *** [src/utility/src_libbitcoin_c_la-variable_uint_size.lo] Error 1
`

I assumed it was related.

**Comment by evoskuil** [comment]
I don't believe it's related, but the error indicates that you have an outdated build. There was an error for a short period of time resulting from the removal of `variable_uint_size.hpp/cpp`. This should no longer be an issue.

**Comment by evoskuil** [comment]
Status?
